### ISSUE TITLE
scenario outline error reporting in Before hook

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber-ruby-core#73]
Hello,

I see a difference between running a `Scenario outline` and a `Scenario`. If I run a scenario and error is raised in `Before` hook, then scenario is marked as failed and steps are skipped.

With a `Scenario outline` though, the steps are executed but at the end scenario is marked as failing. No backtrace is printed out. This can be rather confusing.

**Comment by akostadinov** [comment]
FYI seems like the outline issue is fixed in: https://github.com/cucumber/cucumber/issues/271

**Comment by mattwynne** [comment]
@akostadinov thanks for updating. Regarding your hack, I think I can see that what you'd like is a way to change the status of the running scenario from within a step definition, is that right? So that even if it has already failed you can tell it to continue running. Do I understand that correctly?

**Comment by akostadinov** [comment]
@mattwynne, yes. When debugging a long running scenario, I'd like to be able to fall into a pry/byebug session on a failure and be able to make it continue with scenario execution. Maybe a separate `step_failed` hook will be ideal.
