### ISSUE TITLE
Background.feature is always nil

### ISSUE THREAD

**Issue by brasmusson** [cucumber/cucumber-ruby-core#84]
As @e2 noted (cucumber/gherkin#334), the ast class for Background has an `attr_accessor` for `:feature`, but since the `#feature` is never set on the background object, `#feature` is always nil. Therefore things like `background.feature.name` in for instance `#before_background` in formatter will not work.

**Comment by e2** [comment]
Thanks!

**Comment by mattwynne** [comment]
In general, we've tried to keep the AST in the core from having circular references. Parent nodes know about their children, but not the other way around.

I think the right fix here is to make a change in or around https://github.com/cucumber/cucumber/blob/master/lib/cucumber/formatter/legacy_api/adapter.rb so that the background object passed to the formatter still has that old API, but we don't need to let that leak into the core's AST.

WDYT @tooky @brasmusson?

**Comment by brasmusson** [comment]
I think avoiding circular references is the right thing to do, I only made the fix this way because the [`attr_accessor :feature`](https://github.com/cucumber/cucumber-ruby-core/blob/2e85fcb5f0f32f52179da67e94c092950d4efed1/lib/cucumber/core/ast/background.rb#L27) declaration indicated the the intention was for backgrounds to know their feature.

**Comment by aslakhellesoy** [comment]
whatever you do - please keep in mind @brasmusson @mattwynne also see cucumber/gherkin3#12

**Comment by brasmusson** [comment]
Let's fix this in the `Cucumber::Formatter::LegacyApi` instead.
